server:
  port: ${wfe.services.${spring.application.name}.port}
  servlet:
    context-path: ${wfe.services.${spring.application.name}.context-path}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${wfe.datasource.url}
    username: ${wfe.datasource.username}
    password: ${wfe.datasource.password}
